"""empty message

Revision ID: 17e9edee44ec
Revises: bb69408ae2bb
Create Date: 2020-09-22 02:39:30.436537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e9edee44ec'
down_revision = 'bb69408ae2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'admin_id')
    # ### end Alembic commands ###
