"""empty message

Revision ID: 74b3aed246a7
Revises: 85c5a8b3a8bb
Create Date: 2020-09-15 20:27:46.900865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b3aed246a7'
down_revision = '85c5a8b3a8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('top', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'top')
    # ### end Alembic commands ###
