"""empty message

Revision ID: 7523fb4ccab8
Revises: 3b1011531266
Create Date: 2020-09-10 19:57:31.848483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7523fb4ccab8'
down_revision = '3b1011531266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'name')
    # ### end Alembic commands ###
