"""empty message

Revision ID: 87079483e57b
Revises: c4368b60e153
Create Date: 2020-09-22 01:58:35.771380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87079483e57b'
down_revision = 'c4368b60e153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'admins', ['name'], ['name'])
    op.drop_column('news', 'admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('admin_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###
