"""empty message

Revision ID: a355faf18abb
Revises: bdc3978b4682
Create Date: 2020-09-13 04:51:52.734277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a355faf18abb'
down_revision = 'bdc3978b4682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('date_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'date_time')
    # ### end Alembic commands ###
