"""empty message

Revision ID: bb69408ae2bb
Revises: 7a8d8720fda5
Create Date: 2020-09-22 02:15:21.941481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb69408ae2bb'
down_revision = '7a8d8720fda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('new_type', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('date_time', sa.String(), nullable=True),
    sa.Column('top', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admin_name'], ['admins.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
