"""empty message

Revision ID: f848efc9ecec
Revises: 87079483e57b
Create Date: 2020-09-22 02:06:53.593802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f848efc9ecec'
down_revision = '87079483e57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('admin_name', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'admins', ['admin_name'], ['name'])
    op.drop_column('news', 'name')
    op.drop_column('news', 'admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('admin_id', sa.INTEGER(), nullable=True))
    op.add_column('news', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'admins', ['admin_id'], ['id'])
    op.drop_column('news', 'admin_name')
    # ### end Alembic commands ###
